"""programのprofileへの外部参照を削除

Revision ID: 8f764ccb8409
Revises: 8f4526032038
Create Date: 2026-02-03 11:35:55.137911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f764ccb8409'
down_revision: Union[str, Sequence[str], None] = '8f4526032038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('programs_default_profile_id_fkey'), 'programs', type_='foreignkey')
    op.drop_column('programs', 'default_profile_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('default_profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('programs_default_profile_id_fkey'), 'programs', 'profiles', ['default_profile_id'], ['id'])
    # ### end Alembic commands ###
