"""update: cornersのembedded_descriptionをnot nullに変更

Revision ID: a5f58455c9d1
Revises: 0b17492c2834
Create Date: 2026-03-27 05:54:42.265924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'a5f58455c9d1'
down_revision: Union[str, Sequence[str], None] = '0b17492c2834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NULL値をゼロベクトル（1024次元）で埋める
    op.execute("""
        UPDATE corners 
        SET embedded_description = array_fill(0::float8, ARRAY[1024])::vector 
        WHERE embedded_description IS NULL;
    """)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('corners', 'embedded_description',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('corners', 'embedded_description',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               nullable=True)
    # ### end Alembic commands ###
