"""update: Make mail table's corner_id column nullable

Revision ID: e0346440e332
Revises: b8b1790dc574
Create Date: 2026-01-28 16:57:51.749533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'e0346440e332'
down_revision: Union[str, Sequence[str], None] = 'b8b1790dc574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('corners', 'embedded_description',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               nullable=True)
    op.alter_column('mails', 'corner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mails', 'corner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('corners', 'embedded_description',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               nullable=False)
    # ### end Alembic commands ###
